#####################################################################
########################## GLOBAL PARAMS ############################
#####################################################################
globals:
#Define input/output database names in TD
  canonical_id: stellantics_id
  sink_database: gld_ml_stellantis
  model_type: 'automl'         #Use 'custom' to run custom PS code, use `automl` to run PrecisionML notebook
  built_union_activity: yes
  archive_results: yes
  store_historic_scores: no
  auto_build_segments: no
  time_zone: 'UTC'
  create_dashboard: 'no'
  api_endpoint: 'api.treasuredata.com'
  model_config_table: 'datamodel_build_history'
  num_bins: 10

### Output Table Params 
union_activity_table: rfm_combined_user_events
input_table: rfm_input_table
output_table: rfm_output_table
stats_table: rfm_stats

############## TIME FILTER PARAMS ##########################
##Below params will ONLY be applied if above param `apply_time_filter = 'yes', otherwise entire interaction history will be included
apply_time_filter: 'no'
time_filter_type: interval                   #Use 'range' to specify fixed start/end dates OR 'interval' to lookback days/weeks/months from time_range_end_date
time_range_start_date: 2022-01-01         #Defines start date for`TD_TIME_RANGE` use format YYYY-MM-DD
time_range_end_date: 2222-22-22           #To always end TIME_RANGE at the latest available date, leave default as '222-02-02'. To end on a custom date use format YYYY-MM-DD
lookback_period: '-180d'                    #-1M looksback a month, -30d looks back 30 days, - 2w looksback 2 weeks etc. Used only with TD_INTERVAL                #-1M looksback a month, -30d looks back 30 days, - 2w looksback 2 weeks etc. Used only with TD_INTERVAL


############## UNION BEHAVIOR TABLES PARAMS ##########################
################ INPUT TABLE PARAMS ###################################
aggregate_metrics_tables:
  - src_table: gld_stellantis.enriched_crm_order
    name: 'vehicle_orders'
    unixtime_col: trmfd_delivery_date_unix
    join_key: stellantics_id
    order_amount: 25000.0  # Average vehicle transaction value
    custom_filter: "stellantics_id IS NOT NULL AND stellantics_id != ''''"
    apply_time_filter: 'no'
    query_type:

# Lead generation - high intent signals
  - src_table: gld_stellantis.enriched_crm_lead
    name: 'leads'
    unixtime_col: time
    join_key: stellantics_id
    order_amount: 500.0  # Lead value scoring
    custom_filter: "stellantics_id IS NOT NULL AND status NOT IN (''Closed'', ''Cancelled'', ''Rejected'')"
    apply_time_filter: 'no'
    query_type:

  # Web navigation - engagement tracking
  - src_table: gld_stellantis.enriched_online_web_navigation
    name: 'web_visits'
    unixtime_col: time
    join_key: stellantics_id
    order_amount: 1.0  # Basic engagement score
    custom_filter: "stellantics_id IS NOT NULL AND stellantics_id != ''''"
    apply_time_filter: 'no'
    query_type:

  # Form submissions - high engagement activities
  - src_table: gld_stellantis.enriched_online_forms
    name: 'form_submissions'
    unixtime_col: time
    join_key: stellantics_id
    order_amount: 100.0  # Form submission value
    custom_filter: "stellantics_id IS NOT NULL AND stellantics_id != ''''"
    apply_time_filter: 'no'
    query_type:

  # Survey responses - customer feedback engagement
  - src_table: gld_stellantis.enriched_crm_survey
    name: 'survey_responses'
    unixtime_col: time
    join_key: stellantics_id
    order_amount: 50.0  # Survey engagement value
    custom_filter: "stellantics_id IS NOT NULL AND stellantics_id != ''''"
    apply_time_filter: 'no'
    query_type:

  # Click tracking - email engagement
  - src_table: gld_stellantis.enriched_online_click_tracker
    name: 'email_clicks'
    unixtime_col: time
    join_key: stellantics_id
    order_amount: 5.0  # Email click value
    custom_filter: "stellantics_id IS NOT NULL AND stellantics_id != ''''"
    apply_time_filter: 'no'
    query_type:

  # Email opens - basic engagement
  - src_table: gld_stellantis.enriched_online_open_tracker
    name: 'email_opens'
    unixtime_col: time
    join_key: stellantics_id
    order_amount: 2.0  # Email open value
    custom_filter: "stellantics_id IS NOT NULL AND stellantics_id != ''''"
    apply_time_filter: 'no'
    query_type:

