SELECT
'${table_db}.${table_name}' as table_name,
'none' as column_name,
CAST(NULL AS BIGINT) as total_rows,
CAST(NULL AS BIGINT) as null_cnt,
CAST(NULL AS DOUBLE) as null_perc,
CAST(NULL AS DOUBLE) as max_value,
CAST(NULL AS DOUBLE) as min_value,
CAST(NULL AS DOUBLE) as average_value,
CAST(NULL AS DOUBLE) as std_dev,
CAST(NULL AS DOUBLE) as var,
CAST(NULL AS DOUBLE) as q1,
CAST(NULL AS DOUBLE) as q2,
CAST(NULL AS DOUBLE) as q3,
CAST(NULL AS DOUBLE) as outl_upper_rng,
CAST(NULL AS DOUBLE) as outl_lower_rng,
CAST(NULL AS DOUBLE) as iqr,
CAST(NULL AS DOUBLE) as kurtosis_val,
CAST(NULL AS DOUBLE) as skewness_val,
CAST(NULL AS BIGINT) as num_outliers,
CAST(NULL AS DOUBLE) as perc_outliers