name: Create Staging Agent

on:
  workflow_dispatch:
    inputs:
      td_api_key:
        description: 'Treasure Data API Key'
        required: true
        type: string
      database_name:
        description: 'Source Database Name'
        required: true
        type: string

jobs:
  create-agent:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r staging_agent/src/requirements.txt
    
    - name: Create Staging Agent
      run: |
        cd staging_agent/src
        python main.py "${{ github.event.inputs.td_api_key }}" "${{ github.event.inputs.database_name }}"
