name: Create Knowledge Base

on:
  workflow_dispatch:
    inputs:
      td_api_key:
        description: 'Treasure Data API Key'
        required: true
        type: string
      project_id:
        description: 'Project ID'
        required: true
        type: string
      database_name:
        description: 'Database Name'
        required: true
        type: string
      knowledge_base_name: 
        description: 'Knowledge Base Name'
        required: true
        type: string

jobs:
  create-agent:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r knowledge_base_db/src/requirements.txt
    
    - name: Create Staging Agent
      run: |
        cd knowledge_base_db/src
        python main.py "${{ github.event.inputs.project_id }}" "${{ github.event.inputs.td_api_key }}" "${{ github.event.inputs.database_name }}" "${{ github.event.inputs.knowledge_base_name }}"
